include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [
    lib/injection.config.dart,
    test/**.mocks.dart
  ]

linter:
  rules:
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - always_use_package_imports
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
