name: verbaquiz
description: VerbaQuiz App
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  injectable: ^2.1.2
  http: ^0.13.5
  file: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.3
  test: 1.24.1
  faker: ^2.1.0
  mockito: ^5.4.2

  build_runner:
  injectable_generator: ^2.1.6

  very_good_analysis: ^5.0.0+1
  dart_code_metrics: ^5.7.5

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onboarding_screen/
    - assets/common/
